apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kubedb-orchestrator.fullname" . }}-scripts
  labels:
    {{- include "kubedb-orchestrator.labels" . | nindent 4 }}
data:
  install_kubedb.sh: |
{{ .Values.scripts.installKubedb | indent 4 }}

